# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM实战之网络请求' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'ReactiveCocoa', '~> 2.5'
pod 'AFNetworking', '~> 3.1.0'

  # Pods for MVVM实战之网络请求

  target 'MVVM实战之网络请求Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM实战之网络请求UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
