# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM实战之登陆界面' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'ReactiveCocoa', '~> 2.5'

  # Pods for MVVM实战之登陆界面

  target 'MVVM实战之登陆界面Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM实战之登陆界面UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
