# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '使用cocoapods' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking', '~> 2.5.0'
pod 'ReactiveCocoa', '~> 2.5'

  # Pods for 使用cocoapods

  target '使用cocoapodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '使用cocoapodsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
